apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bot-detection-prod
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: detection
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
  - target:
      kind: Deployment
      name: ml-inference
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
  - target:
      kind: HorizontalPodAutoscaler
      name: detection
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 20
  - target:
      kind: HorizontalPodAutoscaler
      name: ml-inference
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 20
